[package]
name = "redar"
version = "0.3.0"
description = "REDAR — Nuclei 기반 웹 취약점 진단 도구"
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde_json = "1"

[profile.release]
strip = true
lto = true
